name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Go for use with actions
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.14

    - name: Get dependencies for backend
      run: go get -v -d -t .

    - name: Build backend
      run: go build -v

    - name: Deploy code on server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SSH_PORT }}
        FOLDER: "thewall static templates"
        SERVER_IP: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        SERVER_DESTINATION: "/home/${{secrets.SSH_USER}}"

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: "sudo systemctl restart thewall.service"
